#!/bin/sh

ajuda() {
  echo "Descrição:"
  echo "  Substitui um elemento e sua multiplicidade nos arquivos .inp de um diretório."
  echo ""
  echo "Modo de uso:"
  echo "  substitui [opções] diretório"
  echo ""
  echo "Opções:"
  echo "  Obrigatórias:"
  echo "    -t: tipo (pdw ou pt)"
  echo "    -s: elemento a substituir"
  echo "    -e: novo elemento"
  echo "    -m: multiplicidade"
  echo ""
  echo "  Opcionais:"
  echo "    -a: mostra essa mensagem de ajuda e termina o programa"
  exit 1
}

# recebe as opções do usuário
while getopts ":t:s:e:m:a" o; do
  case "$o" in
    a) ajuda ;;
    t) t=$OPTARG ;;
    s) S=$OPTARG ;;
    e) E=$OPTARG ;;
    m) M=$OPTARG ;;
    :) echo "Nenhum argumento para a opção -$OPTARG!\n" && ajuda ;;
    *) echo "Opção inválida: -$OPTARG\n" && ajuda ;;
  esac
done

shift $((OPTIND - 1))

# verifica se todas as opções foram especificadas
[ -z $t ] || [ -z $S ] || [ -z $E ] || [ -z $M ] &&
    echo "Opção(ões) obrigatória(s) faltando!\n" && ajuda

# verifica se o tipo especificado é válido
[ "$t" != "pdw" ] && [ "$t" != "pt" ] && echo "Tipo inválido!\n" && ajuda

# verifica se o diretório especificado existe
[ -z $1 ] && echo "Diretório não especificado!\n" && ajuda
[ ! -d $1 ] && echo "O diretório especificado não existe!\n" && ajuda

# converte o nome dos elementos para minúsculo
s=$(echo $S | tr '[:upper:]' '[:lower:]')
e=$(echo $E | tr '[:upper:]' '[:lower:]')

cd "$1"

find . -type f -name "$t*.inp" |
while read f; do
  b=$(basename $f)
  d=$(dirname $f)

  echo -n "Procesando o arquivo $b... "

  # remove os arquivos não terminados em .inp
  find $d -type f ! -name '*.inp' -delete

  # substitui a multiplicidade
  sed -i -e "s/\(\* xyz .*\) .*$/\1 $M/g" "$f"

  # substitui o nome do elemento
  sed -i -e "s/$S/$E/g" "$f"
 
  # renomeia o arquivo
  n=$(echo $b | sed -e "s/_$s\(\(_\|\.\)\)/_$e\1/g")
  mv "$d/$b" "$d/$n" 2>/dev/null

  echo "pronto!"
done
