#!/bin/sh

ajuda() {
  echo "Descrição:"
  echo "  Verifica se um cálculo do ORCA foi concluído corretamente e faz a análise vibracional."
  echo ""
  echo "Modo de uso:"
  echo "  ./verifica arquivo.out"
  exit 1
}

erro() {
  >&2 echo "$1"
  >&2 echo '\nO cálculo não foi bem sucedido.'
  exit 2
}

# verifica se o arquivo especificado pelo usuário é válido
[ -z "$1" ] && { echo "Arquivo não especificado!\n"; ajuda; }
[ -f "$1" ] || { echo 'O arquivo especifiado não existe!\n'; ajuda; }

base=$(basename $1)
ext=${base##*.}
[ ! $ext = 'out' ] && echo "Aviso: o arquivo especificado não tem extensão .out!\n"

# verifica se as strings necessárias foram encontradas no arquivo
echo 'Verificando se o cálculo foi concluído corretamente...'

grep -q 'ORCA TERMINATED NORMALLY' "$1" \
  && echo '  [*] O orca terminou normalmente.' \
  || erro '  [!] O orca não terminou normalmente.'

grep -q 'THE OPTIMIZATION HAS CONVERGED' "$1" \
  && echo '  [*] A optimização convergiu.' \
  || erro '  [!] A optimização não convergiu.'

grep -q 'OPTIMIZATION RUN DONE' "$1" \
  && echo '  [*] A optimização foi concluída.' \
  || erro '  [!] A optimização não foi concluída.'

echo 'O cálculo foi concluído com sucesso!\n'

# executa a análise vibracional
echo 'Executando análise vibracional...'

# retorna o primeiro valor de frequência negativo se ele existir
neg=$(
  sed -En '
    /^VIBRATIONAL FREQUENCIES$/,${              # começa depois da string "VIBRATIONAL FREQUENCIES"
      /^.* (-[0-9]+\.[0-9][0-9]) cm\*\*-1/{     # captura os valores negativos
        s//\1/p;q                               # printa o primeiro valor negativo e termina
      }                                         
      /^NORMAL MODES$/q                         # termina quando encontra a string "NORMAL MODES"
    }
  ' "$1"
)

[ -z "$neg" ] \
  && echo "  [*] Nenhum valor de frequência negativo encontrado!" \
  || erro "  [!] Valor de frequência negativo ($neg) encontrado!"

echo '\nO cálculo foi bem sucedido!'
