#!/bin/sh

ajuda() {
  echo "Descrição:"
  echo "  Verifica se um cálculo do ORCA foi concluído corretamente e faz a análise vibracional."
  echo ""
  echo "Modo de uso:"
  echo "  verifica [opções] arquivo.out"
  echo ""
  echo "Opções:"
  echo "  -a: mostra essa mensagem de ajuda e termina o programa"
  exit 1
}

erro() {
  >&2 echo "$1"
  >&2 echo '\nO cálculo não foi bem sucedido.'
  exit 2
}

# recebe as opções do usuário
t=false

while getopts "at" o; do
  case "$o" in
    a) ajuda ;;
  esac
done

shift $((OPTIND - 1))

# verifica se o arquivo especificado pelo usuário é válido
[ -z "$1" ] && { echo "Arquivo não especificado!\n"; ajuda; }
[ -f "$1" ] || { echo 'O arquivo especifiado não existe!\n'; ajuda; }

base=$(basename $1)
ext=${base##*.}
[ ! $ext = 'out' ] && echo "Aviso: o arquivo especificado não tem extensão .out!\n"

# detecta se o arquivo é de um estado de transição
case "$1" in
  *'_optTS.out') t=true;;
esac

echo "Verificando o arquivo $1..."
[ "$t" = true ] \
  && echo "Estado de transição detectado, esperando exatamente uma frequência negativa..." \
  || echo "Estado transição não detectado, esperando 0 frequências negativas..."

# verifica se as strings necessárias foram encontradas no arquivo
echo '\nVerificando se o cálculo foi concluído corretamente...'

grep -q 'ORCA TERMINATED NORMALLY' "$1" \
  && echo '  [*] O orca terminou normalmente.' \
  || erro '  [!] O orca não terminou normalmente.'

grep -q 'THE OPTIMIZATION HAS CONVERGED' "$1" \
  && echo '  [*] A optimização convergiu.' \
  || erro '  [!] A optimização não convergiu.'

grep -q 'OPTIMIZATION RUN DONE' "$1" \
  && echo '  [*] A optimização foi concluída.' \
  || erro '  [!] A optimização não foi concluída.'

echo 'O cálculo foi concluído com sucesso!\n'

# executa a análise vibracional
echo 'Executando análise vibracional...'

grep -q 'VIBRATIONAL FREQUENCIES' "$1" \
  && echo '  [*] Frequências de vibração encontradas.' \
  || erro '  [!] Frequências de vibração não encontradas.'

# conta a quantidade de frequências negativas
neg=$(
  tac "$1" |                                    # inverte o arquivo de entrada
  sed -En '
    /^NORMAL MODES$/,${                         # começa depois da string "NORMAL MODES"
      /\*\*\*imaginary mode\*\*\*/p             # captura os valores negativos
      /^VIBRATIONAL FREQUENCIES$/q              # termina quando encontra a linha "VIBRATIONAL FREQUENCIES"
    }
  ' | wc -l
)

if [ "$t" = false ]; then
  [ $neg -eq 0 ] \
    && echo "  [*] Nenhum valor de frequência negativo encontrado!" \
    || erro "  [!] $neg valor(es) de frequência negativo(s) encontrado(s)!"
else
  [ $neg -eq 1 ] \
    && echo "  [*] Apenas um valor de frequência negativo encontrado!" \
    || erro "  [!] $neg valor(es) de frequência negativo(s) encontrado(s)!"
fi

echo '\nO cálculo foi bem sucedido!'
